### PR TITLE
Update wokitout.html

### PR DESCRIPTION
**Pull request by JoQuibs**
Edited the paragraph on line 73

### CODE REVIEW

**Comment by JoQuibs** [comment]
Hi guys! I am having problems putting in my images, hope you could help me
out. These are the links of the following

[Pork Xiao Long Bao]
https://cdn.phonebooky.com/blog/wp-content/uploads/2021/06/08192052/Xiao-Long-Bao-from-Din-Tai-Fung.jpg
[Choco Xiao Long Bao]
https://thspublications.com/wp-content/uploads/2019/04/mochixlb-900x886.png
[Salted Egg Yolk Bun]
http://images.summitmedia-digital.com/spotph/images/2018/04/16/goldenbunsmain.jpg
[Pork & Shrimp Wonton] https://www.dintaifungusa.com/us/image/1344
[Pork & Shrimp Siomai] https://www.dintaifungusa.com/us/image/1350

**Comment by JoQuibs** [comment]
Hey Guys need your help on getting the links to submit for our assignment 4

**Comment by marissadashen** [comment]
Hello Jomar, 
I think the links are on our shared Google document, although I see that I only got 90 out of 100 points for this assignment for not having a link to the repository or site, so I am a bit confused, as usual.

**Comment by Tigray11** [comment]
Same here. It’s weird…I’m unsure what other links we can use. I tried
updating it, but Kyrrah said there’s another link and I don’t have access
to it.
Does Nicholas has access or the links at all, perhaps.

**Pull request merged**
