### PR TITLE
Adds notes from first meeting

### PR DESCRIPTION
**Pull request by nvialp**
meeting notes from 1st meeting

### CODE REVIEW

**Comment by marissadashen** [comment]
I did not receive an invite to tonight's meeting. Can someone please share what was discussed?

**Comment by nvialp** [comment]
> I did not receive an invite to tonight's meeting. Can someone please share what was discussed?

Morning Marissa, We are coordinating through the google doc and the meeting link was on there.  Apologies, there might have been a miscommunication there.

I sent an email out to the team last night explaining our next steps, let me know if you got it.

**Comment by marissadashen** [comment]
Thank you Nicholas, 
Genet forwarded your email to me, and there appears to be a typo in my email address on the email you sent. I seem to be having some unfortunate communication mishaps. lol.
It looks like I just need to choose one of my recipes, create a fake restaurant, and write a review about it.

**Comment by nvialp** [comment]
> Thank you Nicholas, Genet forwarded your email to me, and there appears to be a typo in my email address on the email you sent. I seem to be having some unfortunate communication mishaps. lol. It looks like I just need to choose one of my recipes, create a fake restaurant, and write a review about it.

apologies I just looked back at it now, and I tried to send it to gmailc.om!  Yes choose one of your recipes, come up with a fake restaurant name and then a few short reviews or one long review.  Once you have those send them to me and I can get them in the webpage.

**Pull request merged**
